// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/eralove/eralove-backend/internal/config"
	"github.com/eralove/eralove-backend/internal/domain"
	"github.com/eralove/eralove-backend/internal/handler"
	"github.com/eralove/eralove-backend/internal/infrastructure"
	"github.com/eralove/eralove-backend/internal/repository"
	"github.com/eralove/eralove-backend/internal/service"
	"github.com/google/wire"
	"go.uber.org/zap"
)

import (
	_ "github.com/eralove/eralove-backend/docs"
)

// Injectors from wire.go:

// InitializeApp creates a new application with all dependencies injected
func InitializeApp(cfg *config.Config, logger *zap.Logger) (*App, error) {
	mongoDB, err := infrastructure.ProvideMongoDB(cfg, logger)
	if err != nil {
		return nil, err
	}
	userRepository := repository.ProvideUserRepository(mongoDB, logger)
	passwordManager := infrastructure.ProvidePasswordManager()
	jwtManager := infrastructure.ProvideJWTManager(cfg)
	emailService := infrastructure.ProvideEmailService(cfg, logger)
	userService := service.ProvideUserService(userRepository, passwordManager, jwtManager, emailService, logger)
	validate := infrastructure.ProvideValidator()
	i18n := infrastructure.ProvideI18n(logger)
	userHandler := handler.ProvideUserHandler(userService, validate, i18n, logger)
	photoRepository := repository.ProvidePhotoRepository(mongoDB, logger)
	storageService, err := infrastructure.ProvideStorageService(cfg, logger)
	if err != nil {
		return nil, err
	}
	photoService := service.ProvidePhotoService(photoRepository, userRepository, storageService, logger)
	photoHandler := handler.ProvidePhotoHandler(photoService, validate, i18n, logger)
	uploadHandler := handler.ProvideUploadHandler(storageService, i18n, logger)
	dependencies := ProvideDependencies(userHandler, photoHandler, uploadHandler, storageService)
	app, err := ProvideApp(cfg, logger, dependencies)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

// ApplicationSet combines all provider sets
var ApplicationSet = wire.NewSet(infrastructure.InfrastructureSet, repository.RepositorySet, service.ServiceSet, handler.HandlerSet, ProvideDependencies,
	ProvideApp,
)

// ProvideDependencies creates the dependencies struct
func ProvideDependencies(
	userHandler *handler.UserHandler,
	photoHandler *handler.PhotoHandler,
	uploadHandler *handler.UploadHandler,
	storageService domain.StorageService,
) *Dependencies {
	return &Dependencies{
		UserHandler:    userHandler,
		PhotoHandler:   photoHandler,
		UploadHandler:  uploadHandler,
		StorageService: storageService,
	}
}

// ProvideApp creates the main application
func ProvideApp(cfg *config.Config, logger *zap.Logger, deps *Dependencies) (*App, error) {
	return NewWithDependencies(cfg, logger, deps)
}
