// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/eralove/eralove-backend/internal/config"
	"github.com/eralove/eralove-backend/internal/handler"
	"github.com/eralove/eralove-backend/internal/infrastructure"
	"github.com/eralove/eralove-backend/internal/repository"
	"github.com/eralove/eralove-backend/internal/service"
	"github.com/google/wire"
	"go.uber.org/zap"
)

import (
	_ "github.com/eralove/eralove-backend/docs"
)

// Injectors from wire.go:

// InitializeApp creates a new application with all dependencies injected
func InitializeApp(cfg *config.Config, logger *zap.Logger) (*App, error) {
	client, err := infrastructure.ProvideDirectusClient(cfg, logger)
	if err != nil {
		return nil, err
	}
	cmsService := service.ProvideCMSService(client)
	cmsHandler := handler.ProvideCMSHandler(cmsService)
	dependencies := ProvideDependencies(cmsHandler)
	app, err := ProvideApp(cfg, logger, dependencies)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

// ApplicationSet combines all provider sets
var ApplicationSet = wire.NewSet(infrastructure.InfrastructureSet, repository.RepositorySet, service.ServiceSet, handler.HandlerSet, ProvideDependencies,
	ProvideApp,
)

// ProvideDependencies creates the dependencies struct
func ProvideDependencies(

	cmsHandler *handler.CMSHandler,

) *Dependencies {
	return &Dependencies{

		CMSHandler: cmsHandler,
	}
}

// ProvideApp creates the main application
func ProvideApp(cfg *config.Config, logger *zap.Logger, deps *Dependencies) (*App, error) {
	return NewWithDependencies(cfg, logger, deps)
}
